// College data
const colleges = [
  {
    id: "1",
    name: "Indian Institute of Technology Delhi",
    location: "Hauz Khas, New Delhi",
    city: "Delhi",
    state: "Delhi",
    ranking: 1,
    fees: 225000,
    courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
    facilities: ["Library", "Sports Complex", "Labs", "WiFi", "Cafeteria", "Medical Center"],
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800&h=400&fit=crop",
    description: "IIT Delhi is one of the premier engineering institutions in India, known for its excellence in technical education and research.",
    rating: 4.8,
    placement: {
      average: 1800000,
      highest: 5000000,
      percentage: 95,
    },
    hostel: {
      available: true,
      fees: 15000,
      type: "Separate Boys & Girls Hostels",
    },
    admissionProcess: "JEE Advanced for B.Tech, GATE for M.Tech, CAT for MBA",
    established: 1961,
    type: "Government",
  },
  {
    id: "2",
    name: "Indian Institute of Technology Bombay",
    location: "Powai, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    ranking: 2,
    fees: 235000,
    courses: ["B.Tech", "M.Tech", "MBA", "MSc", "PhD"],
    facilities: ["Library", "Sports Complex", "Research Labs", "Auditorium", "Hospital", "Gym"],
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&h=400&fit=crop",
    description: "IIT Bombay is a leading institution of higher learning, ranked among the top engineering colleges in India with world-class infrastructure.",
    rating: 4.9,
    placement: {
      average: 2100000,
      highest: 6000000,
      percentage: 97,
    },
    hostel: {
      available: true,
      fees: 18000,
      type: "16 Hostels on Campus",
    },
    admissionProcess: "JEE Advanced, GATE, CAT, JAM",
    established: 1958,
    type: "Government",
  },
  {
    id: "3",
    name: "Delhi University - St. Stephen's College",
    location: "North Campus, Delhi",
    city: "Delhi",
    state: "Delhi",
    ranking: 3,
    fees: 50000,
    courses: ["BA", "BSc", "MA", "MSc"],
    facilities: ["Central Library", "Sports Ground", "Computer Labs", "Canteen", "Chapel"],
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=400&fit=crop",
    description: "St. Stephen's College is one of the oldest and most prestigious colleges of Delhi University, known for its academic excellence.",
    rating: 4.7,
    placement: {
      average: 800000,
      highest: 2500000,
      percentage: 85,
    },
    hostel: {
      available: true,
      fees: 25000,
      type: "On-campus Hostels",
    },
    admissionProcess: "CUET (Common University Entrance Test)",
    established: 1881,
    type: "Government",
  },
  {
    id: "4",
    name: "Birla Institute of Technology & Science Pilani",
    location: "Vidya Vihar, Pilani",
    city: "Pilani",
    state: "Rajasthan",
    ranking: 4,
    fees: 450000,
    courses: ["B.E.", "M.E.", "MBA", "MSc", "PhD"],
    facilities: ["Digital Library", "Innovation Center", "Sports Complex", "Auditorium", "Labs"],
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=400&fit=crop",
    description: "BITS Pilani is a premier private university known for its engineering programs and innovative teaching methods.",
    rating: 4.6,
    placement: {
      average: 1500000,
      highest: 4500000,
      percentage: 92,
    },
    hostel: {
      available: true,
      fees: 55000,
      type: "Multiple Hostels with AC/Non-AC options",
    },
    admissionProcess: "BITSAT Entrance Exam",
    established: 1964,
    type: "Private",
  },
  {
    id: "5",
    name: "National Institute of Technology Trichy",
    location: "Tanjore Main Road, Tiruchirappalli",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    ranking: 5,
    fees: 175000,
    courses: ["B.Tech", "M.Tech", "MBA", "MSc", "PhD"],
    facilities: ["Central Library", "Tech Park", "Sports Complex", "Medical Center", "Cafeteria"],
    image: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=800&h=400&fit=crop",
    description: "NIT Trichy is one of the top NITs in India, renowned for its engineering education and research facilities.",
    rating: 4.5,
    placement: {
      average: 1200000,
      highest: 4000000,
      percentage: 90,
    },
    hostel: {
      available: true,
      fees: 12000,
      type: "14 Hostels on Campus",
    },
    admissionProcess: "JEE Main for B.Tech, GATE for M.Tech",
    established: 1964,
    type: "Government",
  },
  {
    id: "6",
    name: "Manipal Institute of Technology",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    ranking: 8,
    fees: 350000,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA"],
    facilities: ["Library", "Innovation Lab", "Sports Center", "Food Court", "Medical Facility"],
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&h=400&fit=crop",
    description: "MIT Manipal is a leading private engineering college with strong industry connections and modern facilities.",
    rating: 4.4,
    placement: {
      average: 950000,
      highest: 3500000,
      percentage: 88,
    },
    hostel: {
      available: true,
      fees: 85000,
      type: "Multiple Hostels with Modern Amenities",
    },
    admissionProcess: "MET (Manipal Entrance Test) or JEE Main",
    established: 1957,
    type: "Private",
  },
  {
    id: "7",
    name: "Vellore Institute of Technology",
    location: "Katpadi, Vellore",
    city: "Vellore",
    state: "Tamil Nadu",
    ranking: 10,
    fees: 198000,
    courses: ["B.Tech", "M.Tech", "MBA", "MCA", "Integrated Courses"],
    facilities: ["Digital Library", "Research Centers", "Sports Arena", "Cafeteria", "Hospital"],
    image: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=800&h=400&fit=crop",
    description: "VIT is a prestigious private university known for its quality education, diverse student body, and excellent placement record.",
    rating: 4.3,
    placement: {
      average: 850000,
      highest: 4100000,
      percentage: 86,
    },
    hostel: {
      available: true,
      fees: 75000,
      type: "AC and Non-AC Hostels",
    },
    admissionProcess: "VITEEE Entrance Exam",
    established: 1984,
    type: "Private",
  },
  {
    id: "8",
    name: "Jadavpur University",
    location: "Raja S.C. Mallick Road, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    ranking: 12,
    fees: 15000,
    courses: ["B.E.", "M.E.", "MA", "MSc", "PhD"],
    facilities: ["Library", "Research Labs", "Sports Ground", "Canteen", "Medical Room"],
    image: "https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&h=400&fit=crop",
    description: "Jadavpur University is a public university known for its strong engineering and arts programs with affordable fees.",
    rating: 4.4,
    placement: {
      average: 900000,
      highest: 3900000,
      percentage: 82,
    },
    hostel: {
      available: true,
      fees: 8000,
      type: "On-campus Hostels",
    },
    admissionProcess: "WBJEE for B.E., GATE for M.E.",
    established: 1955,
    type: "Government",
  },
  {
    id: "9",
    name: "SRM Institute of Science & Technology",
    location: "Kattankulathur, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    ranking: 15,
    fees: 250000,
    courses: ["B.Tech", "M.Tech", "MBA", "BBA", "Medical Courses"],
    facilities: ["Tech Park", "Innovation Center", "Stadium", "Medical Center", "Shopping Complex"],
    image: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800&h=400&fit=crop",
    description: "SRM is a large private university with state-of-the-art infrastructure and strong focus on research and innovation.",
    rating: 4.2,
    placement: {
      average: 700000,
      highest: 3000000,
      percentage: 80,
    },
    hostel: {
      available: true,
      fees: 95000,
      type: "Multiple Hostels with AC facilities",
    },
    admissionProcess: "SRMJEEE or JEE Main",
    established: 1985,
    type: "Private",
  },
  {
    id: "10",
    name: "Anna University - CEG Campus",
    location: "Guindy, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    ranking: 14,
    fees: 25000,
    courses: ["B.E.", "B.Tech", "M.E.", "M.Tech", "MBA", "MCA"],
    facilities: ["Central Library", "Research Centers", "Sports Complex", "Auditorium", "Placement Cell"],
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&h=400&fit=crop",
    description: "Anna University is a premier technical university in South India, offering affordable quality education.",
    rating: 4.3,
    placement: {
      average: 650000,
      highest: 2800000,
      percentage: 78,
    },
    hostel: {
      available: true,
      fees: 10000,
      type: "Separate Boys & Girls Hostels",
    },
    admissionProcess: "TNEA Counselling, TANCET for PG",
    established: 1978,
    type: "Government",
  },
];
